project_id = "ivjycxegcunbamdmwbzg"

[functions.send-hotel-emails]
verify_jwt = true

[functions.send-hotel-emails-custom]
verify_jwt = true

[functions.user-approval]
verify_jwt = false

[functions.send-arrival-reminders]
verify_jwt = false
